version: '3'
services:
  api:
    image: langlink-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 langlink.wsgi
    container_name: langlink-backend
    volumes:
      - .:/app
    networks:
      - backend
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
    image: nginx
    container_name: nginx
    depends_on:
      - api
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    #   - /app/static:/app/static
    networks:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:

networks:
  backend: