# Generated by Django 4.1.1 on 2023-02-16 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='encrypted_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='パスワード'),
            preserve_default=False,
        ),
    ]
