# Generated by Django 4.1.1 on 2023-02-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_commentpost_likecomment_post_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_liked_by', through='app.LikeComment', to='app.account'),
        ),
    ]
