# Generated by Django 4.1.1 on 2023-02-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_commentpost_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='follower',
            field=models.ManyToManyField(related_name='follower_by', to='app.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(related_name='following_to', to='app.account'),
        ),
    ]
