# Generated by Django 4.1.1 on 2023-02-23 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_account_follower_account_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='ユーザーID'),
            preserve_default=False,
        ),
    ]
