# Generated by Django 4.1.1 on 2023-03-01 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='follower_by', to='app.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='following_to', to='app.account'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('like', 'いいね'), ('comment', 'コメント'), ('follow', 'フォロー')], default='like_post', max_length=50, verbose_name='通知タイプ')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.account')),
                ('account_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications2', to='app.account')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.commentpost')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
